import type { Metadata } from "next";
import { Fraunces, Nunito_Sans, Libre_Baskerville } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

// Configure fonts with display=swap for better performance
const fraunces = Fraunces({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-fraunces",
});

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nunito-sans",
});

const libreBaskerville = Libre_Baskerville({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-libre-baskerville",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${fraunces.variable} ${nunitoSans.variable} ${libreBaskerville.variable}`}
      >
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
